## 中断Promsie执行
基于race实现中断promise：指的不是中断promsie请求的执行，而是放弃执行的结果，比如现在有个需求：
一个promsie正在走向成功，需要等3秒，需求是如果2s不返回结果就认为失败了 中断这个promise

那么我们会这样实现：
```js
let abort = null;
let p1 = new MyPromise((resolve, reject) => {
	abort = reject;
	setTimeout(() => {
		console.log('开始执行')
		resolve('等待3秒后成功了')
	}, 3000)
})
p1.abort = abort;
p1.then((res) => {
	console.log(res);
}, err => {
	console.log(err);
})

setTimeout(() => {
	p1.abort('等待2秒没有结果，认为错误'); // 
}, 2000) */
```

## promsie.abort中断方法实现
```js

/* 
	封装一个中止promsie返回结果的方法wrap
	返回出去的这个promsie并不会影响原始promise执行的结果
 */
function wrap(promise) {
	let abort = null;
	// 把控制自己这个promsie失败的reject函数引用给了abort变量
	let _promise = new MyPromise((resolve,reject)=>{
		abort = reject;
	});
	
	// race方法只要成功一个立即成功 失败一个立即失败 我就要在外边手动控制让自己的这个失败从而让绑在一起的那个p1后续的结果被忽略 提前获取返回的resultPromsie的结果 
	let resultPromsie = MyPromise.race([_promise,promise]);
	// 把控制自己这个promsie失败的reject函数引用给了abort变量，然后挂载到返回的promsie上
	resultPromsie.abort = abort;
	return resultPromsie;
}

let p0 = new MyPromise((resolve, reject) => {
	abort = reject;
	setTimeout(() => {
		console.log('开始执行')
		resolve('等待5秒后成功了')
	}, 5000)
})

let p6 = wrap(p0);


p6.then((res) => {
	console.log(res);
}, err => {
	console.log(err);
})
setTimeout(() => {
	p6.abort('等待3秒没有结果，认为错误'); // 
}, 3000)
```

## 中断promise的链式调用
这里的中断指的是让promise在某个链式回调的过程中停下来，不再向后传递参数。

```js
/* 
中断promsie的链式调用 
返回一个既不成功也不失败的promsie 终止链式调用
 */
const p8 = new MyPromise((resolve,reject)=>{resolve(100)});
p8.then(()=>{return 200}).then(()=>{return 300}).then((res)=>{console.log(res)});
// 到300的时候就中止链式调用
p8.then(()=>{return 200}).then(()=>{return new Promise(()=>{})}).then((res)=>{console.log(res)});
```